package:
  name: fpfilter
  version: {{ environ.get('GIT_DESCRIBE_TAG', '0.0.0') }}
source:
  # or from git:
  git_url: https://github.com/yuxiangtan/FPfilter.git
  # once we have a release, uncomment next line and change it to match
  # release tag name
  #git_tag: v1

build:

  number: 0       # (defaults to 0)

requirements:

  run:
   - rtg-tools	

test:
  commands:
    - FPfilter -h

about:
  home: https://github.com/yuxiangtan/FPfilter
  license: Apache Version 2.0
